### ISSUE TITLE
Sample for Express.js doesn't work

### ISSUE THREAD

**Issue by ebal5** [haxiomic/dts2hx#102]
I want to use dts2hx and try to run sample in repo.
But it didn't work. How can I fix it?

A list of actions what I've done are below.

1. copy whole filed in [Express Sample Directory](https://github.com/haxiomic/dts2hx/tree/master/examples/express)
2. run `npm install`
3. run `haxe build.hxml`

then, I got error like this.

```
C:\HaxeToolkit\haxe\std/js/lib/Float64Array.hx:95: characters 28-65 : Type name js.lib.AsyncIterator is redefined from module js.lib.AsyncIterator
Server.hx:1: lines 1-39 : ... Defined in this class
C:\HaxeToolkit\haxe\std/js/lib/Float32Array.hx:95: characters 28-65 : Module js.lib.Iterator does not define type Iterator
Server.hx:1: lines 1-39 : ... Defined in this class
C:\HaxeToolkit\haxe\std/js/lib/Uint32Array.hx:94: characters 28-63 : Module js.lib.Iterator does not define type Iterator
Server.hx:1: lines 1-39 : ... Defined in this class
C:\HaxeToolkit\haxe\std/js/lib/Int32Array.hx:94: characters 28-63 : Module js.lib.Iterator does not define type Iterator
```

My Environments:

- OS: Windows 10
- Develop on WSL or Docker? No
- `haxe --version` => `4.2.3`
- `node --version` => `v16.13.0`

**Comment by haxiomic** [comment]
Hey @ebal5, looks like the haxe std library has added some more types in recent versions, dts2hx by default uses 4.0.5 stdlib types

you can solve this by adding `--useSystemHaxe` to the postinstall script

I've updated the Server example with this (and another small tweak in the haxe code required)

I'll make `--useSystemHaxe` default in the future I think

**Comment by ebal5** [comment]
Thanks a lot!
I'll try it later.
