### ISSUE TITLE
enum abstract enumeration convertion is incorrect if started not from 0

### ISSUE THREAD

**Issue by serjek** [haxiomic/dts2hx#104]
1. `npx dts2hx react-native-rate`
2. Observe generated `AndroidMarket.hx` file. It has following `enum abstract` declatation:
```hx
@:jsRequire("react-native-rate", "AndroidMarket") @:enum extern abstract AndroidMarket(Int) from Int to Int {
	var Google;
	var Amazon;
	var Other;
}
```
3. Observe original source, it has following enum declaration:
```ts
export const AndroidMarket = {
  Google: 1,
  Amazon: 2,
  Other: 3,
}
```

Expected: resulting enum should be correctly enumerated like so:
```hx
var Google = 1;
var Amazon = 2;
var Other = 3;
```

Experienced: resulting enumeration starts with 0 which results in incorrect params passed to lib.

**Comment by haxiomic** [comment]
The generated code references the source enum, for example: https://try.haxe.org/#aAcC35B5

```haxe
@:jsRequire("react-native-rate", "AndroidMarket") @:enum extern abstract AndroidMarket(Int) from Int to Int {
	var Google;
	var Amazon;
	var Other;
}

class Test {
  static function main() {
    trace("Haxe is great!");
    var x: AndroidMarket = Google;
    trace(x);
  }
}
```

Generates
```js
console.log("Test.hx:11:",AndroidMarket.Google);
```

**Comment by serjek** [comment]
Hey sorry for false alarm, it works as expected. For some reason I got removed the `@:jsRequire` part when first checked, generated again and it's working now. Closing the issue!

**Comment by haxiomic** [comment]
No worries :), glad it's working
