### ISSUE TITLE
Some things are missing, when converting Vue type definitions

### ISSUE THREAD

**Issue by muchitto** [haxiomic/dts2hx#11]
So, I don't know if this is a bug or if it's just a case of me not using it properly, but as I tried to convert Vue type definitions and using it just like I would use the typescript version, it gives errors on missing types.

The conversion went fine (or it didn't at least give me an error), but when I tried to use it, it gives me errors on missing some types.

This is the way I'm trying to use it:
https://vuejs.org/v2/guide/typescript.html#Annotating-Return-Types 

If I try to use it like that with this code just to see what happens:
```haxe
import vue.Vue;

class Main {
    public static function main () {
        var comp = Vue.extend({
            data : () -> {
                return {
                    test : "test"
                };
            }
        });
    }
}
``` 
It gives me this error: 
`externs/vue/vue/Vue.hx:5: characters 69-73 : Type not found : Data`

So I guess something is missing?

**Comment by haxiomic** [comment]
Hey @muchitto! Thanks for testing, you're not missing anything – looks like you've found a bug involving type-parameters and constructors

I'll try to fix in the converter soon, but in the meantime, you can manually resolve the problem by replacing 

```haxe
function new(?options:ThisTypedComponentOptionsWithArrayProps<Vue, Data, Methods, Computed, PropNames>);
```

With 

```haxe
function new<Data, Methods, Computed, PropNames>(?options:ThisTypedComponentOptionsWithArrayProps<Vue, Data, Methods, Computed, PropNames>);
```

Please let me know if you run into more issues!

**Comment by haxiomic** [comment]
I've resolved the issue in the converter :) – if you upgrade to 0.5.1 the externs will now include the missing type parameters

**Comment by muchitto** [comment]
Well that was fast... :D Yes, seems to work out of the box now.

**Comment by muchitto** [comment]
This is probably kinda nitpicky, but I don't know if this is because of the way Haxe's display server works or if this is something that can be nudged here, but when actually trying to use the Vue library in Haxe vs Typescript.

Typescript immediately knows what properties that structure can have and it autocompletes perfectly just that:
![typescript-autocomplete](https://user-images.githubusercontent.com/359786/81497143-44e08980-92c5-11ea-8da2-9871137f5478.png)

And Haxe just doesn't know what to show you at the moment:
![haxe-autocomplete](https://user-images.githubusercontent.com/359786/81497158-69d4fc80-92c5-11ea-8d94-d4ec83199461.png)

These kinds of things are pretty awesome if the work, because they show you that you are on the right track. Now the Haxe autocomplete kinda "lies" to you compared to Typescript. :)

Also, Typescript actually shows an error if you try anything that isn't supposed to be there. For instance, the field elee doesn't actually exist so naturally it shows an error there:
![ts-error](https://user-images.githubusercontent.com/359786/81497259-026b7c80-92c6-11ea-8d59-ab1375799175.png)

Haxe is just "Ok" and compiles fine:
![haxe-error](https://user-images.githubusercontent.com/359786/81497265-0b5c4e00-92c6-11ea-9d4e-146ddc1f0033.png)

**Comment by Gama11** [comment]
The Haxe extension definitely supports this kind of completion in principle:

https://github.com/vshaxe/vshaxe/wiki/Completion#structure-field-completion

**Comment by haxiomic** [comment]
Yeah, haxe definitely supports this but this is the converter giving up trying to convert `new Vue(options)`. Reading the vue definitions, it has some of the gnarliest typescript I've seen

The type of options here is
```typescript
export type ThisTypedComponentOptionsWithArrayProps<V extends Vue, Data, Methods, Computed, PropNames extends string> =
  object &
  ComponentOptions<V, DataDef<Data, Record<PropNames, any>, V>, Methods, Computed, PropNames[], Record<PropNames, any>> &
  ThisType<CombinedVueInstance<V, Data, Methods, Computed, Readonly<Record<PropNames, any>>>>;
```

Where ComponentOptions is
```typescript
export interface ComponentOptions<
  V extends Vue,
  Data=DefaultData<V>,
  Methods=DefaultMethods<V>,
  Computed=DefaultComputed,
  PropsDef=PropsDefinition<DefaultProps>,
  Props=DefaultProps> {
  data?: Data;
  props?: PropsDef;
  propsData?: object;
  computed?: Accessors<Computed>;
  ...
}
```

Now most of this should convert ok, but we fall down with mapped types like
`Record<PropNames, any>`, which we can handled everywhere except on type parameters

So sadly I think vue is a case where a handwritten adaptation to haxe is the only way to get perfect typing

Vue also makes heavy use of javascript's native this, which is handled differently in haxe so examples like https://vuejs.org/v2/guide/typescript.html#Annotating-Return-Types won't work out of the box (you'll need to use `js.Lib.nativeThis` in place of this)

**Comment by muchitto** [comment]
Yeah, thought so. I thought the way Vue components were created in Typescript was also pretty peculiar (kinda un-Typescript:ish way), so I'm not THAT surprised.

I guess this is more towards the Typescript kinda way of making components and not some strange Typescript wrapper on a Javascript initialization object kinda way:
https://vuejs.org/v2/guide/typescript.html#Class-Style-Vue-Components

I don't know if you also need some kind of macro pre-processing for that kind of code.

But yeah, probably the best way to use Vue with Haxe would be probably to just write those externs by hand, I just thought it was a great test case. :)

**Comment by haxiomic** [comment]
It is a great test case, I'm happy it uncovered the type params bug

The class approach looks like it would work better. I don't know about the decorators however, they might need a manual port if they're critical to functionality

**Comment by muchitto** [comment]
Yeah, unfortunately they are pretty critical. You define the components that can be used in the current Vue component, like so (haven't tried the conversion tool on it yet):
https://class-component.vuejs.org/guide/class-component.html#other-options

Although you import the `@Component` decorator from another npm package called `vue-class-component`. But yeah, all in all, it can get messy.  

It's pretty much the same with Angular. It defines a `@Component` decorator,  where you have to define some metadata about your component.

**Comment by muchitto** [comment]
Just to give a heads up, tried this again with Vue for fun and it now gives me an error when trying to compile:
`... .haxelib\vue/2,6,11/vue/types/options/ThisTypedComponentOptionsWithRecordProps.hx:6: characters 87-168 : Can only extend structures`

This is all I'm doing:
```haxe
import vue.Vue;

function main () {
    
}
```

**Comment by haxiomic** [comment]
Not a problem I'm having – check you're on the latest dts2hx

You can also now use `global.Vue` to enable using Vue via a <script> tag which is waaay simpler than the webpack route

**Comment by haxiomic** [comment]
Oh... Fails on 4.1.0, not on 4.0.5

**Comment by muchitto** [comment]
I'm trying out the 4.2 nightly, as you can see from the glorious module level function. :) 

Thanks for the tip!

But yeah, intriguing, it actually crossed my mind if it's a compiler bug, because I'm using a nightly, but ok it doesn't work on 4.1.0...

**Comment by haxiomic** [comment]
After reading the externs it _should_ work on 4.1.0, when I find what's up I'll open an issue
