### ISSUE TITLE
ERROR] No matching export in "loaders/GLTFLoader.js" for import "GLTFParser

### ISSUE THREAD

**Issue by sonygod** [haxiomic/dts2hx#113]
[ERROR] No matching export in "node_modules/three/examples/jsm/loaders/GLTFLoader.js" for import "GLTFParser

just test GltfLoader,and got this error.

is there something we still missing?

```haxe 

@:js.import("three/examples/jsm/loaders/GLTFLoader.js", "GLTFLoader") extern class GLTFLoader extends three.Loader


  @:js.import("three/examples/jsm/loaders/GLTFLoader.js", "GLTFParser") extern class GLTFParser
```

**Comment by haxiomic** [comment]
In this case it's the typescript definitions that are wrong – GLTFParser is not exported, and is private and internal to GLTFLoader

https://github.com/mrdoob/three.js/blob/659b6895c4da6ad2285c2c2a7af4638248174a4c/examples/jsm/loaders/GLTFLoader.js#L2241

**Comment by sonygod** [comment]
you mean 

from

   @:js.import("three/examples/jsm/loaders/GLTFLoader.js", "GLTFParser") extern class GLTFParser 

to

   extern class GLTFParser 

?

**Comment by haxiomic** [comment]
I mean that three.js r138 doesn't give a way to import GLTFParser, so there is no way to use it:
https://github.com/mrdoob/three.js/blob/659b6895c4da6ad2285c2c2a7af4638248174a4c/examples/jsm/loaders/GLTFLoader.js#L4398

**Comment by haxiomic** [comment]
I've opened a PR to correct @types/three
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59319

**Comment by haxiomic** [comment]
Closing this as there's nothing to be done

**Comment by haxiomic** [comment]
Reopening because there does seem to be something up:

dts2hx is generating a public constructor for GLTFParser when it shouldn't
