### ISSUE TITLE
Can't npm install on Mac M1

### ISSUE THREAD

**Issue by ConfidantCommunications** [haxiomic/dts2hx#126]
When I attempt to run the Three example and do `npm install` I get:

npm ERR! code 1
npm ERR! path /Users/alland/Documents/haXe/dts2hx/examples/three/node_modules/esbuild
npm ERR! command failed
npm ERR! command sh /var/folders/cy/2wqynsd16s170bqxtqfrvw4w0000gq/T/postinstall-f3e3d7e6.sh
npm ERR! error: Unsupported platform: darwin arm64

Any suggestions?

**Comment by haxiomic** [comment]
Hey! Try editing package json to use the latest version of esbuild and deleting package-lock.json

**Comment by ConfidantCommunications** [comment]
This works, thank you.
