### ISSUE TITLE
Type not found : global.XRFrameRequestCallback

### ISSUE THREAD

**Issue by ConfidantCommunications** [haxiomic/dts2hx#128]
When I attempt a build on the "three" example, I get:

`/Users/alland/Documents/haXe/dts2hx/examples/three/.haxelib/three/0,160,0/three/WebGLRenderer.hx:149: characters 42-71 : Type not found : global.XRFrameRequestCallback`

If I comment out that line then compile I get Type not found : global.XRPlane.
Note: This is after upgrading three to the 0.160.0 version. 

So I'm guessing I need to generate externs for those global items and possibly others. Sorry for the noob question but how should I do that? I attempted npx dts2hx three --global but that didn't fix it. The error just changed to "Type not found : XRFrameRequestCallback".

**Comment by FlashTang** [comment]
Seems this is a bug ? 
I just fixed by delete the global. 
For me , add --globalPackageName "" fixed the issue

**Comment by ConfidantCommunications** [comment]
It seems that anything in the Three "internal" classes got excluded and I had to manually create those externs. There were a half dozen or so.
