### ISSUE TITLE
@:jsRequire("sqlite3", "Database") extern class Database extends Dynamic

### ISSUE THREAD

**Issue by sonygod** [haxiomic/dts2hx#15]
test SQLite gen got some error.

  i:\test\testnpm\.haxelib\sqlite/4,0,7/sqlite/sqlite3/Database.hx:3: characters 66-73 : Should extend by using a class

**Comment by sonygod** [comment]
import sqlite.sqlite3.Database;
    import sqlite.sqlite3.Statement;

    class Main {
        static function main() {
            var db:Database = new Database(":memory:");
            //	db.run()
            var createTable:String = "
        CREATE TABLE IF NOT EXISTS fa_customer (
        id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
        fk integer(11) NOT NULL DEFAULT 0,
        gailv integer(11) NOT NULL DEFAULT 0,
        money DECIMAL(11,10) NOT NULL DEFAULT 0,
        avatar text(255) NOT NULL ,
        nickname text(255),
        openid text(100) NOT NULL,
        club_id integer(11) DEFAULT -1,
        isgm integer(1) NOT NULL DEFAULT 0,
        isrobot integer(1) NOT NULL DEFAULT 0,
        mobile text(11),
        password text(32),
        referenceID integer(11) NOT NULL DEFAULT 0,
        coins  DECIMAL(11,4) NOT NULL DEFAULT 0,
        staticCoins  DECIMAL(11,4) NOT NULL DEFAULT 0,
        level integer(1) NOT NULL DEFAULT -1
        
        
        )";

            db.run(createTable, null, function(e:js.lib.Error) {
                trace(Std.string(e));
            });
        }
    }

**Comment by haxiomic** [comment]
Hey @sonygod, funny enough this one is caused by a bug in the sqlite externs, I've opened a PR to fix it there: https://github.com/kriasoft/node-sqlite/pull/115

I've also tweaked the converter to better handle this kind of error, so try again with dts2hx 0.11.0
