### ISSUE TITLE
convert custom *.d.ts issue.

### ISSUE THREAD

**Issue by sonygod** [haxiomic/dts2hx#16]
from
 [haxe community](https://community.haxe.org/t/use-typescript-definitions-with-haxe-dts2hx-is-ready-to-use/2440/9)

    npm install dts2hx
    git clone https://github.com/cocos-creator/helloworld-typescript
    npx dts2hx ./helloworld-typescript/creator --tsconfig helloworld-typescript/tsconfig.json

got any extern was generated.

  win7  ,haxe 4.2.

    I:\test\testnpm>npx dts2hx ./helloworld-typescript/creator --tsconfig helloworld-typescript/tsconfig.json
    > Converting module ./helloworld-typescript/creator
    > Saved externs for ./helloworld-typescript/creator into externs/

**Comment by sonygod** [comment]
also same issue in playcanvas-gltf


I:\test\testnpm>npx dts2hx playcanvas-gltf
> Converting module playcanvas-gltf
> Error: Failed to find typescript for module "playcanvas-gltf". Searched the following paths:
        I:/test/testnpm/node_modules/playcanvas-gltf.ts
        I:/test/testnpm/node_modules/playcanvas-gltf.tsx
        I:/test/testnpm/node_modules/playcanvas-gltf.d.ts
        I:/test/testnpm/node_modules/playcanvas-gltf/viewer/lib/playcanvas-gltf.js
        I:/test/testnpm/node_modules/playcanvas-gltf/viewer/lib/playcanvas-gltf.js.ts
        I:/test/testnpm/node_modules/playcanvas-gltf/viewer/lib/playcanvas-gltf.js.tsx
        I:/test/testnpm/node_modules/playcanvas-gltf/viewer/lib/playcanvas-gltf.js.d.ts
        I:/test/testnpm/node_modules/playcanvas-gltf/viewer/lib/playcanvas-gltf.ts
        I:/test/testnpm/node_modules/playcanvas-gltf/viewer/lib/playcanvas-gltf.tsx
        I:/test/testnpm/node_modules/playcanvas-gltf/viewer/lib/playcanvas-gltf.d.ts
        I:/test/testnpm/node_modules/playcanvas-gltf/viewer/lib/playcanvas-gltf.js/index.ts
        I:/test/testnpm/node_modules/playcanvas-gltf/viewer/lib/playcanvas-gltf.js/index.tsx
        I:/test/testnpm/node_modules/playcanvas-gltf/viewer/lib/playcanvas-gltf.js/index.d.ts
        I:/test/testnpm/node_modules/playcanvas-gltf/index.ts
        I:/test/testnpm/node_modules/playcanvas-gltf/index.tsx
        I:/test/testnpm/node_modules/playcanvas-gltf/index.d.ts
        I:/test/testnpm/node_modules/@types/playcanvas-gltf/package.json
        I:/test/testnpm/node_modules/@types/playcanvas-gltf.d.ts
        I:/test/testnpm/node_modules/@types/playcanvas-gltf/index.d.ts
        I:/test/node_modules/playcanvas-gltf/package.json
        I:/test/node_modules/playcanvas-gltf.ts
        I:/test/node_modules/playcanvas-gltf.tsx
        I:/test/node_modules/playcanvas-gltf.d.ts
        I:/test/node_modules/playcanvas-gltf/index.ts
        I:/test/node_modules/playcanvas-gltf/index.tsx
        I:/test/node_modules/playcanvas-gltf/index.d.ts
        I:/test/node_modules/@types/playcanvas-gltf/package.json
        I:/test/node_modules/@types/playcanvas-gltf.d.ts
        I:/test/node_modules/@types/playcanvas-gltf/index.d.ts
        I:/node_modules/playcanvas-gltf/package.json
        I:/node_modules/playcanvas-gltf.ts
        I:/node_modules/playcanvas-gltf.tsx
        I:/node_modules/playcanvas-gltf.d.ts
        I:/node_modules/playcanvas-gltf/index.ts
        I:/node_modules/playcanvas-gltf/index.tsx
        I:/node_modules/playcanvas-gltf/index.d.ts
        I:/node_modules/@types/playcanvas-gltf/package.json
        I:/node_modules/@types/playcanvas-gltf.d.ts
        I:/node_modules/@types/playcanvas-gltf/index.d.ts
        I:/test/testnpm/node_modules/playcanvas-gltf.js
        I:/test/testnpm/node_modules/playcanvas-gltf.jsx
        I:/test/testnpm/node_modules/playcanvas-gltf/viewer/lib/playcanvas-gltf.js
        I:/test/testnpm/node_modules/playcanvas-gltf/viewer/lib/playcanvas-gltf.js.js
        I:/test/testnpm/node_modules/playcanvas-gltf/viewer/lib/playcanvas-gltf.js.jsx
        I:/test/testnpm/node_modules/playcanvas-gltf/viewer/lib/playcanvas-gltf.js
        I:/test/testnpm/node_modules/playcanvas-gltf/viewer/lib/playcanvas-gltf.jsx
        I:/test/testnpm/node_modules/playcanvas-gltf/viewer/lib/playcanvas-gltf.js/index.js
        I:/test/testnpm/node_modules/playcanvas-gltf/viewer/lib/playcanvas-gltf.js/index.jsx
        I:/test/testnpm/node_modules/playcanvas-gltf/index.js
        I:/test/testnpm/node_modules/playcanvas-gltf/index.jsx
        I:/test/node_modules/playcanvas-gltf/package.json
        I:/test/node_modules/playcanvas-gltf.js
        I:/test/node_modules/playcanvas-gltf.jsx
        I:/test/node_modules/playcanvas-gltf/index.js
        I:/test/node_modules/playcanvas-gltf/index.jsx
        I:/node_modules/playcanvas-gltf/package.json
        I:/node_modules/playcanvas-gltf.js
        I:/node_modules/playcanvas-gltf.jsx
        I:/node_modules/playcanvas-gltf/index.js
        I:/node_modules/playcanvas-gltf/index.jsx
> Error: Input module not resolve

**Comment by haxiomic** [comment]
With the first issue, what went wrong? It looks like it worked
“ Saved externs for ./helloworld-typescript/creator into externs/”

On playcanvas-gltf, where is that located? Check your node_modules folder to see if it’s in there

Make sure you do `npm install playcanvas-gltf` first

**Comment by haxiomic** [comment]
I've looked into playcanvas-gltf and it isn't really setup as a ts module – package.json has no types field.

You can get it to work by adding `"types": "types/playcanvas-gltf/index.d.ts"` to node_modules/playcanvas-gltf/package.json and then running

`dts2hx  playcanvas-gltf --tsconfig node_modules/playcanvas-gltf/tsconfig.json`

Try using playcanvas-gltf from typescript – you will also get "Cannot find module 'playcanvas-gltf'.". Dts2hx will only work on modules that also work in typescript
