### ISSUE TITLE
convert type wrong.

### ISSUE THREAD

**Issue by sonygod** [haxiomic/dts2hx#17]
base *.d.ts is

https://github.com/cocos-creator/helloworld-typescript/blob/master/creator.d.ts#L12573

     playAnimation(animName : string, playTimes : number) : dragonBones.AnimationState;

after convert 

     function playAnimation(animName:String, playTimes:Float):Dynamic;

**Comment by sonygod** [comment]
it's not dts2hx error,it's base creator.d.ts.

**Comment by haxiomic** [comment]
Yeah just found that too perhaps they're missing a `///<reference types="dragonbones" />` or something similar
Or maybe they meant `cc.AnimationState`

**Comment by sonygod** [comment]
[creator.d.zip](https://github.com/haxiomic/dts2hx/files/4657488/creator.d.zip)


I don't know why they don't update the last creator.d.ts .only can be found in sofeware.
