### ISSUE TITLE
there is some error on google's Filament engine.

### ISSUE THREAD

**Issue by sonygod** [haxiomic/dts2hx#19]
npm install  filament

    dts2hx filament

it seems missing some get/set support.

     constructor(canvas) {
            this.canvas = canvas;
            const engine = this.engine = Filament.Engine.create(this.canvas);
            this.scene = engine.createScene();

            const sunlight = Filament.EntityManager.get().create();
            Filament.LightManager.Builder(LightType.SUN)
                .color([0.98, 0.92, 0.89])
                .intensity(100000.0)
                .direction([0.6, -1.0, -0.8])
                .castShadows(true)//we can't get this in haxe 
                .sunAngularRadius(1.9)//we can't get this in haxe 
                .sunHaloSize(10.0)//we can't get this in haxe 
                .sunHaloFalloff(80.0)//we can't get this in haxe 
                .build(engine, sunlight);
            this.scene.addEntity(sunlight);
    }

![image](https://user-images.githubusercontent.com/748320/82532387-dbd5fd00-9b73-11ea-9a26-f13971130642.png)

**Comment by haxiomic** [comment]
Are you sure you're using the same Filament version in the examples? 

I do not have those extra fields when I test in typescript
<img width="582" alt="Screenshot 2020-05-21 at 08 39 33" src="https://user-images.githubusercontent.com/3742992/82535456-c4305180-9b3e-11ea-99f8-aa7b6e4a55ef.png">

After reading the externs they should not be there
**Filament.d.ts** (1.7.0)
```typescript
export class LightManager$Builder {
    public build(engine: Engine, entity: Entity): void;
    public castShadows(value: boolean): LightManager$Builder;
    public color(rgb: float3): LightManager$Builder;
    public direction(value: float3): LightManager$Builder;
    public intensity(value: number): LightManager$Builder;
    public position(value: float3): LightManager$Builder;
}
```

**Comment by sonygod** [comment]
em,may be you look its *.d.ts

https://github.com/google/filament/blob/master/web/filament-js/filament.d.ts#L218-L222

@haxiomic

**Comment by haxiomic** [comment]
That’s not the type returned from `Filament.LightManager.Builder()`
