### ISSUE TITLE
[question]how to call this function on gen class ?

### ISSUE THREAD

**Issue by sonygod** [haxiomic/dts2hx#21]
there is  a function in Cocos creator  ,the API  like unity.
       
       @:overload(function(className:String):Dynamic { })
	function getComponent<T>(type:{ var prototype : T; }):T;//_BaseNode.hx

//I want to call that.
 
         var com:Component=label.node.getComponent<Component>(); //where is wrong ,how to fixed?

       var com:Component=label.node.getComponent(Component);//wrong!

//according  this [link](https://book.king011.com/angular/zh-Hant/view/devgame-cocos-creator-ts/access-node-component) in typescript.

        const button = this.node.getComponent(cc.Button)//it's ok in typescript.
         button.clickEvents.push(handler)

maybe we need some Marco function to help?

**Comment by haxiomic** [comment]
references to classes are tricky. For this you're best off casting
`label.node.getComponent(cast Component);`

**Comment by haxiomic** [comment]
Cast no longer needed in 0.11.9

**Comment by sonygod** [comment]
don't know why still got this error ,still have to use cast too.

![image](https://user-images.githubusercontent.com/748320/82748899-18099780-9dd8-11ea-9d8d-b2297f0db719.png)


dts2hx 0.12.1 version

**Comment by haxiomic** [comment]
Works fine for me when I use a version of creator where `getComponent` is
`getComponent<T extends Component>(type: {prototype: T}): T;`
