### ISSUE TITLE
[question]how to add eventhander on cocos creator use dts2hx extern?

### ISSUE THREAD

**Issue by sonygod** [haxiomic/dts2hx#22]
from   cc.Component.EventHandler

typescript can have a default constructor(). and haxe not.

creator.d.ts have nothing constructor() ,so dts2hx can not generate default constructor function 

may be you can add some flag to do this .such like   
 
    --adc      add default constructor?

**Comment by sonygod** [comment]
https://docs.cocos.com/creator/manual/en/components/button.html

**Comment by haxiomic** [comment]
Thanks for the report, in 0.11.10 dts2hx now generates default constructors (always)
