### ISSUE TITLE
Rest Argument should be add.

### ISSUE THREAD

**Issue by sonygod** [haxiomic/dts2hx#25]
code from cocos creator .d.ts

     export function Class(options?: {name?: string; extends?: Function; ctor?: Function; __ctor__?: Function; properties?: any; statics?: any; mixins?: Function[]; editor?: {executeInEditMode?: boolean; requireComponent?: Function; menu?: string; executionOrder?: number; disallowMultiple?: boolean; playOnFocus?: boolean; inspector?: string; icon?: string; help?: string; }; update?: Function; lateUpdate?: Function; onLoad?: Function; start?: Function; onEnable?: Function; onDisable?: Function; onDestroy?: Function; onFocusInEditor?: Function; onLostFocusInEditor?: Function; resetInEditor?: Function; onRestore?: Function; _getLocalBounds?: Function; }): Function;	

it's seem typescript only options this arguments  but not limit other arguments

here is piece of  haxe test code 

   	

	class Main {
		public static var name:String = "main";

		static function main() {
			Cc.Class({
				'extends': Component,
				properties: {
					
				},

				onLoad: function() {
					
				},
				callback: function(event, customEventData) {
				
				},
				update: function(dt) {},
			});
		}
	}

callback is not allow here in haxe,but js and typescript can .

maybe you should add some rest Argument for that and unlimit parms in Cc.Class

https://docs.cocos.com/creator/manual/en/components/button.html

**Comment by haxiomic** [comment]
Rest arguments are supported but this function does not declare any

This function instead takes an object

The type of the object does include a callback field (are you sure this is correct use of the API?)

Haxe has stricter rules for structure unification than typescript and will complain sometimes about additional fields

This is not something dts2hx can change

**Comment by haxiomic** [comment]
Here’s a related issue and explaination
https://github.com/HaxeFoundation/haxe/issues/3192#issuecomment-50076423

**Comment by sonygod** [comment]
Can you give an example?

**Comment by haxiomic** [comment]
```haxe
var options: {
    var field: String
} = {
    field: 'hello',
    extra: 'world', // this field is disallowed because it's not included in the structure
// this is done because generally if you're directly assigning to a structure like this, extra fields are usually a typo
}
```

This works however

```haxe
var options =  = {
    field: 'hello',
    extra: 'world',
}
function call(options: Options);
call(options); // OK
```

I think if you wrap the field name in quotes it will probably work. Try this

```haxe
Cc.Class({
    "callback": function(event, customEventData) {},
});
```

**Comment by sonygod** [comment]
![image](https://user-images.githubusercontent.com/748320/82736182-2c0eb400-9d5a-11ea-830e-1846591e9a36.png)

 I think if you wrap the field name in quotes it will probably work.

no ,it's not work.

**Comment by haxiomic** [comment]
Ahh ok, nothing we can do then
