### ISSUE TITLE
enum generated as plain int in @types/vscode

### ISSUE THREAD

**Issue by Gama11** [haxiomic/dts2hx#26]
Generating externs for `@types/vscode` 1.45.1 with dts2hx 0.11.13 produces a `vscode.TreeItem.collapsibleState` that is typed as a plain `Int`. In reality, it is an enum:

```haxe
/**
	[TreeItemCollapsibleState](#TreeItemCollapsibleState) of the tree item.
**/
@:optional
var collapsibleState : Int;
```

____

```ts
/**
 * [TreeItemCollapsibleState](#TreeItemCollapsibleState) of the tree item.
 */
collapsibleState?: TreeItemCollapsibleState;
```

```ts
/**
 * Collapsible state of the tree item
 */
export enum TreeItemCollapsibleState {
    /**
     * Determines an item can be neither collapsed nor expanded. Implies it has no children.
     */
    None = 0,
    /**
     * Determines an item is collapsed
     */
    Collapsed = 1,
    /**
     * Determines an item is expanded
     */
    Expanded = 2
}
```

Note: a `TreeItemCollapsibleState.hx` that looks correct is generated actually, so it's just about the type hint of the field.

**Comment by haxiomic** [comment]
Interesting! That shouldn’t happen. I’ll investigate

**Comment by haxiomic** [comment]
Bug with optional types, fixed in 0.12.0 :)

**Comment by Gama11** [comment]
I found another instance of this in `vscode.Window.createStatusBarItem()`'s `alignment` parameter; it's `Int` but should be `StatusBarAlignment`.

**Comment by haxiomic** [comment]
I found a way to fix the general case, so that should be the last of this kind of error
