### ISSUE TITLE
Nested namespaces in @types/vscode

### ISSUE THREAD

**Issue by Gama11** [haxiomic/dts2hx#27]
(again `@types/vscode` 1.45.1 with dts2hx 0.11.13)

The generated `VSCode.hx` looks like this:

```haxe
/**
	Type Definition for Visual Studio Code 1.45 Extension API
	See https://code.visualstudio.com/api for more information
**/
@:jsRequire("vscode") @valueModuleOnly extern class Vscode {
	/**
		The version of the editor.
	**/
	static var version : String;
}
```

When in reality, it should look something like this:

https://github.com/vshaxe/vscode-extern/blob/cd6c7cc347cf873b0dce732ed1b283bf116079ee/src/Vscode.hx

In the original .d.ts definitions, these are nested namespaces for `vscode.commands` etc, we made up our own class names such as `VscodeCommands`.

___

Apart from the missing fields, `version` is also mutable, even though it's `const` in the TS definitions.

**Comment by haxiomic** [comment]
This was a design choice: the mapping I use is 
- *namespaces* -> *packages*
- And *namespace values* (like version) are placed in a haxe module with the same name

We could add aliases for each type within a namespace to the namespace haxe module, but then we have two ways of reaching the type: `vscode.Commands` and `Vscode.commands`

(Also  `const` now generates `final`)

**Comment by Gama11** [comment]
Ah, right, I had missed `vscode.Commands`.

Not sure what the best approach is, maybe @nadako has some thoughts as he originally designed the vscode externs this way.

**Comment by nadako** [comment]
The approach described by @haxiomic is the one I used for hxnodejs and it makes sense to me :) Regarding vscode externs - I'm not sure, probably decided that it was better ergonomics :shrug:

**Comment by haxiomic** [comment]
I think for converting new libs the current behavior is ok so I’ll close this
