### ISSUE TITLE
js.lib.ReadonlyArray

### ISSUE THREAD

**Issue by Gama11** [haxiomic/dts2hx#28]
This is one of the places that causes compiler errors when trying to replace handwritten VSCode externs with the generated ones. We've recently switched to using `haxe.ds.ReadOnlyArray`, not sure if that's an option that makes sense here?

Other than that I think it should at least be wrapped in an abstract to provide array (get) access.

**Comment by haxiomic** [comment]
Agreed, sorting out this is planned with the index signature support

I’m on a full time contract now through June so dts2hx dev will slow down but you could probably patch a fix for this case quite easily, simplest approach would be to add it as a special type in HaxeTypePathMap (see around line 250)

**Comment by Gama11** [comment]
No worries, thanks for all the hard work! :)

It's not urgent, not sure if we ever want to fully replace the handwritten VSCode externs, I was mostly curious how close we are to that.

**Comment by haxiomic** [comment]
js.lib.ReadonlyArray is now replaced with haxe.ds.ReadOnlyArray in 0.12.1

**Comment by Gama11** [comment]
So much for you being busy with other things? ;)
