### ISSUE TITLE
Void -> Void should be Null<js.lib.Function>?

### ISSUE THREAD

**Issue by sonygod** [haxiomic/dts2hx#30]
Don't know why will throw this error after update dts2hx version.

    package;

    import global.cc.Component;
    import global.Cc;

    class HitTest {
        public static function main() {
            Cc.Class({
                'extends': Component,
                properties: {},

                onLoad: function() {},
                update: function(dt) {}
            });
        }
    }

src/HitTest.hx:12: characters 12-25 : Void -> Void should be Null<js.lib.Function>
src/HitTest.hx:12: characters 12-25 : For optional function argument 'options'

     @:optional var onLoad : js.lib.Function;

![image](https://user-images.githubusercontent.com/748320/82743959-107ccb00-9da5-11ea-80ee-7518569d0c82.png)

haxe 4.1 or haxe 4.2 got the same result.

**Comment by haxiomic** [comment]
I don't have the same version of creator – could you send complete repo steps?

**Comment by sonygod** [comment]
sorry ,it's my pc problem ,my dts2hx still old version.

**Comment by sonygod** [comment]
[creator.d.zip](https://github.com/haxiomic/dts2hx/files/4673124/creator.d.zip)

after recheck and reinstall dts2hx 0.12.1 ,still got this error,but it's work fine in my notebook at home.

**Comment by haxiomic** [comment]
Check you're using the right version of creator. Older versions do not have the same type for `getComponent()`. It needs to look like this
`getComponent<T extends Component>(type: {prototype: T}): T;`

**Comment by sonygod** [comment]
em ,maybe my version still old version.sorry about that .
