### ISSUE TITLE
confusing  about  js.Lib.nativeThis

### ISSUE THREAD

**Issue by sonygod** [haxiomic/dts2hx#31]
confusing  about js.lib. js.Lib.nativeThis

after use 

      var this_ = js.Lib.nativeThis;

Vscode autocomplete  and type check is not work. 

![image](https://user-images.githubusercontent.com/748320/82748947-759de400-9dd8-11ea-8bab-568e28c4713c.png)

![image](https://user-images.githubusercontent.com/748320/82748988-be559d00-9dd8-11ea-8c1e-e7fd9185c50d.png)

If you can't type check and smart prompt, then haxe will have no advantage

**Comment by haxiomic** [comment]
nativeThis is Dynamic so we have no type information

nativeThis is required to work around fundamental differences between haxe and javascript. There's nothing we can do to change this.

This is a pattern only some js-libraries use

You can manually specify the type of nativeThis if you know it

**Comment by haxiomic** [comment]
Generally best thing in this case is to find another way to use the library that avoids requiring nativeThis

**Comment by sonygod** [comment]
I'll find the best way avoid this.
