### ISSUE TITLE
ignore module import without type definition, or not?

### ISSUE THREAD

**Issue by akitsu-sanae** [haxiomic/dts2hx#33]
`dts2hx ` fails when imported module does not have type definition, but `tsc` ignores such module importation.  
So, `dts2hx` can fail to convert a module which `tsc` can handle.  
I know that ignoring such module imports in `dts2hx` can be harmful, but how would you do?

**Comment by haxiomic** [comment]
I agree this should just be an error and not prevent conversion

Can you give me an example library that I can test with?

**Comment by akitsu-sanae** [comment]
I did. here is.
https://github.com/akitsu-sanae/dts2hx-empty-module

**Comment by haxiomic** [comment]
Thanks @akitsu-sanae

**Comment by haxiomic** [comment]
I've changed the error message into a warning that says "Definitions not found for module"

The externs in index.ts will still convert as normal

Update to version 0.12.3
