### ISSUE TITLE
Externs naming. Maybe use CamelCase instead of Snake_case

### ISSUE THREAD

**Issue by dmitryhryppa** [haxiomic/dts2hx#36]
Hi!
I'm trying to use dts2hx with `firebase-admin` and found that it generates `firebase_admin` package and `Firebase_admin` class in the same root, which conflicts a bit with each other on the code autocomplete stage. 
Also, `Firebase_admin` looks a bit out of the Haxe code style. Probably it would be better to change naming into something like `FirebaseAdmin`.

I'm using `"dts2hx": "^0.12.3"`

Thanks!

**Comment by haxiomic** [comment]
Fixed in 4468b9c1b145e1dfcd5afc6921b0ed891ddeb769 
Update to 0.13.0 :)
