### ISSUE TITLE
graphql schema generator is converted to Dynamic

### ISSUE THREAD

**Issue by francescoagati** [haxiomic/dts2hx#38]
in this schema example 
```
export type Maybe<T> = T | null;
export type Exact<T extends { [key: string]: any }> = { [K in keyof T]: T[K] };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  Date: any;
};


export type Query = {
  __typename?: 'Query';
  me: User;
  user?: Maybe<User>;
  allUsers?: Maybe<Array<Maybe<User>>>;
  search: Array<SearchResult>;
  myChats: Array<Chat>;
};


export type QueryUserArgs = {
  id: Scalars['ID'];
};


export type QuerySearchArgs = {
  term: Scalars['String'];
};

export enum Role {
  User = 'USER',
  Admin = 'ADMIN'
}

export type Node = {
  id: Scalars['ID'];
};

export type SearchResult = User | Chat | ChatMessage;

export type User = Node & {
  __typename?: 'User';
  id: Scalars['ID'];
  username: Scalars['String'];
  email: Scalars['String'];
  role: Role;
};

export type Chat = Node & {
  __typename?: 'Chat';
  id: Scalars['ID'];
  users: Array<User>;
  messages: Array<ChatMessage>;
};

export type ChatMessage = Node & {
  __typename?: 'ChatMessage';
  id: Scalars['ID'];
  content: Scalars['String'];
  time: Scalars['Date'];
  user: User;
};
```

ChatMessage is converted to Dynamic

**Comment by haxiomic** [comment]
Thanks for testing @francescoagati 

You can resolve the issue by passing a hidden flag `--allowIntersectionRasterization`

Handling intersections in the general case is currently disabled because the converter can enter an infinite loop with some libraries

I'll leave the issue open until this is resolved by default

**Comment by francescoagati** [comment]
thanks,
i have try with the internal flag but i get always dynamic.
this is the repo test i have created https://github.com/francescoagati/test-dts2hx-graphql-generator

i have use the npm version of dts2hx

**Comment by haxiomic** [comment]
Works for me, double check for typos

I cloned the repo and did
`npx dts2hx ./schema1 --allowIntersectionRasterization`

**Chat.hx**
```haxe
package schema1;

typedef Chat = {
	var id : String;
	@:optional
	var __typename : String;
	var users : Array<User>;
	var messages : Array<ChatMessage>;
};
```

**Comment by francescoagati** [comment]
wow really strange i have always use yarn run (yarn run dts2hx ./schema1 --allowIntersectionRasterization) and i get dynamic but with npx (npx dts2hx ./schema1 --allowIntersectionRasterization) i get the type correct. may be that yarn dont pass correctly the argument --allowIntersectionRasterization

**Comment by francescoagati** [comment]
find the bug. i have and old version of yarn that use -- for passing the params. 
really thanks for help

**Comment by haxiomic** [comment]
:) np
