### ISSUE TITLE
omit types for extern lib

### ISSUE THREAD

**Issue by francescoagati** [haxiomic/dts2hx#39]
hi,
is possible omit the generation of types for external lib as react. for example whe i use use a file tsx as source of types i dont need the generation of types for react

**Comment by haxiomic** [comment]
I can add a flag `--skipDependencies` to just convert the current module and assume dependencies already exist

Will let you know when that’s in

**Comment by francescoagati** [comment]
thanks :-)

**Comment by haxiomic** [comment]
Done :): update to 0.13.1 and use `--skipDependencies` flag

**Comment by francescoagati** [comment]
thanks i will try tomorrow
