### ISSUE TITLE
is support debug when use with esbuild?

### ISSUE THREAD

**Issue by sonygod** [haxiomic/dts2hx#40]
from your three.js example, it seems not to support debug in vs code.

what's wrong?

**Comment by haxiomic** [comment]
Could you give an example for what you’re trying to do? Debugging works but if you’re running the code in a browser vscode has to connect to the browser and this needs setting up

https://www.google.co.uk/amp/s/www.freecodecamp.org/news/how-to-set-up-the-debugger-for-chrome-extension-in-visual-studio-code-c0b3e5937c01/amp/

**Comment by haxiomic** [comment]
Or it’s it just sourcemapping?

**Comment by sonygod** [comment]
Just use your three.js example to test

**Comment by haxiomic** [comment]
I mean how are you trying to debug? Are you trying to debug using vscode's debugging tool? The code is executed in a browser, vscode cannot debug anything running in a browser unless it's been setup to do so

**Comment by sonygod** [comment]
build.hxml

     --class-path src
    -main Main

    # externs are written to local library path '.haxelib'
    -lib three
    -lib gsap
    -js bin/dist/main.js
    -dce full
    --debug
    -D js-es=6
    # thee.js from npm uses require(), so we must run a bundler after building haxe code
    -cmd npx esbuild bin/dist/main.js --bundle --outfile=bin/dist/bundle.js

cd bin & anywehre

then 


       {
        // Use IntelliSense to learn about possible attributes.
        // Hover to view descriptions of existing attributes.
        // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
        "version": "0.2.0",
        "configurations": [
            {
                "type": "chrome",
                "request": "launch",
                "name": "Launch Chrome against localhost",
                "url": "http://localhost:8000",
                "webRoot": "${workspaceFolder}"
            }
        ]
    }

**Comment by haxiomic** [comment]
Try adding source maps with `--sourcemap` so this line becomes
`-cmd npx esbuild bin/dist/main.js --bundle --outfile=bin/dist/bundle.js`
`-cmd npx esbuild bin/dist/main.js --bundle --outfile=bin/dist/bundle.js --sourcemap`

**Comment by sonygod** [comment]
still not work ,after add  --sourcemap ,and generate bundle.js.map

BTW,is possible  without  esbuild? I don't want embed js engine to my app. and us some of cdn three.js version and share with 

other app

**Comment by haxiomic** [comment]
It's possible without  esbuild – use the types the package in `global.three` instead and then you can use three.js via a `<script>` tag

**Comment by sonygod** [comment]
after use global.three.*  replace  three.*;

I got this error:

    ArrayIterator.hx:53 Uncaught ReferenceError: require is not defined
    at ArrayIterator.hx:53
    at ArrayIterator.hx:53


![image](https://user-images.githubusercontent.com/748320/86751803-7e3d3780-c071-11ea-9915-e7a0b34d9bc8.png)

![image](https://user-images.githubusercontent.com/748320/86751910-92813480-c071-11ea-8e83-25ab784efc56.png)

**Comment by haxiomic** [comment]
That implies not all three types are coming from three.*, double check you haven't missed any

Feel free to zip the project and post here and I'll check too

**Comment by sonygod** [comment]
[three.zip](https://github.com/haxiomic/dts2hx/files/7631390/three.zip)

**Comment by haxiomic** [comment]
Hey :) – so there's currently a bug in esbuild where the haxe generated paths break when they get copied into esbuild

https://github.com/evanw/esbuild/issues/1745

Likely not too complex to fix but I need to learn some Go lang first :P

**Comment by sonygod** [comment]
can't wait  you fixed this bug as soon  as possible.

**Comment by haxiomic** [comment]
It’s not something I need in the short term and I’m unlikely to fix with my current work load

I’d recommend exploring how to fix in esbuild (or the haxe compiler by avoiding the file:/// paths)

you can make it work manually by replacing file:/ with file:/// in the generate .map file

**Comment by sonygod** [comment]
you mean repacing **file:/** in main.js.map or bundle.js.map

in main.js ,it's already gen **file:///**

I re-add **file:///** to  bundle.js.map still does not work.

@haxiomic

**Comment by haxiomic** [comment]
When you compile with `-debug`, in bundle.js.map you'll see a `"sources"` field with paths like `file:/Users...`, which if you replace file:/ with file:/// it should work. I'm only testing on mac

It would probably be simpler to fix in esbuild however

**Comment by sonygod** [comment]
but I still can't debug jump into *.hx file, only debug in main.js .

current bundle.js.map  sources field have no 'file:/' or something else like ..


```json
{
  "version": 3,
  "sources": ["node_modules\\three\\build\\three.js", "node_modules\\poly2tri\\dist\\version.json", "node_modules\\poly2tri\\src\\xy.js", "node_modules\\poly2tri\\src\\pointerror.js", "node_modules\\poly2tri\\src\\point.js", "node_modules\\poly2tri\\src\\triangle.js", "node_modules\\poly2tri\\src\\assert.js", "node_modules\\poly2tri\\src\\advancingfront.js", "node_modules\\poly2tri\\src\\utils.js", "node_modules\\poly2tri\\src\\sweep.js", "node_modules\\poly2tri\\src\\sweepcontext.js", "node_modules\\poly2tri\\src\\poly2tri.js", "node_modules\\three\\build\\three.module.js", "node_modules\\three\\examples\\jsm\\exporters\\GLTFExporter.js", "node_modules\\three\\examples\\jsm\\lines\\LineSegmentsGeometry.js", "node_modules\\three\\examples\\jsm\\lines\\LineMaterial.js", "node_modules\\three\\examples\\jsm\\lines\\LineSegments2.js", "node_modules\\three\\examples\\jsm\\lines\\LineGeometry.js", "node_modules\\three\\examples\\jsm\\lines\\Line2.js", "dist\\main.js"],
```

I try to readd **file://mypath**  still not work.


[dist.zip](https://github.com/haxiomic/dts2hx/files/7707985/dist.zip)

**Comment by sonygod** [comment]
finally,I found the reason why doesn't work, I have to update esbuild to the last version . in your example,your esbuild version is  too old to use .

```json
  "devDependencies": {
    "esbuild": "^0.14.3",
    "dts2hx": "*"
  },
```

thanks agin.

**Comment by sonygod** [comment]
[three_fixeddebug.zip](https://github.com/haxiomic/dts2hx/files/7708116/three_fixeddebug.zip)

may help somebody else
