### ISSUE TITLE
confusing  about haxe lib path.

### ISSUE THREAD

**Issue by sonygod** [haxiomic/dts2hx#43]
after use dts2hx ,only .haxelib can be use ,can't share other libs?

![QQ图片20200717090831](https://user-images.githubusercontent.com/748320/87737293-2343d700-c80d-11ea-9d65-cbb79f2fd35d.png)

Haxe Compiler 4.2.0-rc.1+d0fd88b9b - (C)2005-2020 Haxe Foundation

**Comment by haxiomic** [comment]
In haxe, if a .haxelib/ exists, it will only look there for libs so you’d have to install the libs you want again (`haxelib install hxnodejs`)

I think local libs is generally a better way of managing dependencies but I could add a new flag `-g` which could install the generated library globally

Haxe dependency management isn’t amazing  at the moment, but work is being done to improve this
