### ISSUE TITLE
there is some difference  api between dts2hx gen and haxe's js.npm

### ISSUE THREAD

**Issue by sonygod** [haxiomic/dts2hx#45]
I follow this 

     http://matthijskamstra.github.io/haxenode/12socket/example.html

and don't know how to create something like 

        var app    = new js.npm.Express();//Express.call()
        var server = js.node.Http.createServer( cast app ); //what's this in dts2hx gen?
        var io     = new js.npm.socketio.Server(server);//what's this in dts2hx gen?

**Comment by haxiomic** [comment]
js.node is part of hxnodejs and js.npm.socketio is externs for socket.io as part of js-kit. If you want to only use dts2hx in your example you will need to convert types for node.js API and socket.io.

Here's how:
```
npm install @types/node
npm install @types/socket.io
npx dts2hx --all
```

That page also includes types for another module: `js.npm.Jade`, but this lib seems dead maybe? Not sure, nevertheless you could do `npm install @types/jade` and `npx dts2hx jade`

**Comment by haxiomic** [comment]
Just tested this and socket.io doesn't work with dts2hx yet, so maybe stick with js-kit for that
