### ISSUE TITLE
Problem with DefinitelyTyped

### ISSUE THREAD

**Issue by ciscoheat** [haxiomic/dts2hx#54]
I'm trying to convert types for [puppeteer](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/puppeteer) from DefinitelyTyped, so I've cloned the directory and installed `@types/node`, but get this error when running dts2hx (Win 10, Node 12.19.0):

```
E:\Temp\puppeteer\> dts2hx .\index
Converting module .\index
Error: TypeError: Cannot read property 'length' of undefined
```

After some debugging I've tracked down the problem to `HaxeTypePathMap.hx`, the `generateTypePath` method, where the `symbolChain` array is empty but is still being accessed with `symbolChain.length - 1`.

**Comment by haxiomic** [comment]
Thanks for the report, not sure what's breaking there, I'll look into it. However, I'm not sure I follow the approach here. Conversion of puppeteer types seems to work for me:

```
npm i dts2hx
npm i @types/puppeteer
npx dts2hx puppeteer
```
```
> Converting module puppeteer
> Saved externs for puppeteer into .haxelib/puppeteer/3,0,2/
> Converting module node
> Saved externs for node into .haxelib/node/14,11,8/
```

For definitelytyped types, you can use `npm i @types/{module-name}`

**Comment by ciscoheat** [comment]
Thank you, it worked perfectly when I used your instructions. Even when a library is easy to use, it's hard to know the actual way in. :)
