### ISSUE TITLE
Set a default package?

### ISSUE THREAD

**Issue by ciscoheat** [haxiomic/dts2hx#56]
When converting the puppeteer library from DefinitelyTyped, it was placed in the top level package. Is there a way to specify a custom package path and convert all the files to that directory structure?

This is such a great library, thank you for doing it! 💯

**Comment by haxiomic** [comment]
It's possible to add this feature, although it _should_ pick a package structure that mirrors how the types are defined in typescript. How does your library structure look? Following the commands from #54 I get:

<img width="325" alt="Screenshot 2020-10-15 at 02 47 23" src="https://user-images.githubusercontent.com/3742992/96067061-cb128480-0e90-11eb-810f-fa1716ebc91f.png">

So everything is in the puppeteer package except Puppeteer.hx. A naive remap to move Puppeteer.hx to a package also moves all the other types too, so say we wanted `puppeteer.Puppeteer.hx`, we'd then get `puppeteer.puppeteer.Browser`

Moving specific types is possible, but things start getting more complicated and I'm not sure it's worth it at that point

**Comment by ciscoheat** [comment]
The packages resolved themselves very well when I used your instructions. Again thank you, I'll be back with a few small things in another issue!
