### ISSUE TITLE
some error from inherit class.

### ISSUE THREAD

**Issue by sonygod** [haxiomic/dts2hx#59]
[index.d.zip](https://github.com/haxiomic/dts2hx/files/5389988/index.d.zip)

npm install -D @types/amap-js-api

will gen 

   `extern class TileLayer extends TileLayer`  should be ` extern class TileLayer extends RasterLayer`

and 

    `@jsInaccessible extern class Traffic`    should be    `@:native("AMap.TileLayer.Traffic") @jsInaccessible extern class Traffic`

**Comment by haxiomic** [comment]
I cannot reproduce:

```
npm i dts2hx @types/amap-js-api
npx dts2hx amap-js-api
```

I get

```haxe
package global.amap;

@:native("AMap.TileLayer") extern class TileLayer extends Layer {
```

(for AMap 1.4.8)

Where did the index.d.ts that you have come from?

**Comment by sonygod** [comment]
maybe I got the old version of Amap(1.0.7)  .sorry!
