### ISSUE TITLE
can't find package.json

### ISSUE THREAD

**Issue by francescoagati** [haxiomic/dts2hx#6]
hi,
when i do npm install https://github.com/haxiomic/dts2hx --save-dev i get
```
npm ERR! prepareGitDep 
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: dts2hx@git+https://github.com/haxiomic/dts2hx.git.
npm ERR! package.json npm can't find a package.json file in your current directory.

```

**Comment by francescoagati** [comment]
was an old npm version sorry

**Comment by haxiomic** [comment]
Just a heads up, code is changing _a lot_ day to day as I work towards beta

Lots currently doesn't work but it won't be too much longer till we're there!
