### ISSUE TITLE
documentation `npx dts2hx @types/xxxxx`

### ISSUE THREAD

**Issue by MatthijsKamstra** [haxiomic/dts2hx#64]
Not every project has `.ts` included like tree.js

In my documentation of haxe and nodejs I use lowdb in an example (https://github.com/MatthijsKamstra/haxenode/tree/master/03lowdb)

Solution:

```
npm install lowdb
npm install @types/lowdb
```

convert

```
npx dts2hx @types/lowdb
```

Also needed to install hxnodejs again, probably a hidden feature of the `.haxelib` folder I am unfamiliar with but it might be worth mentioning

```
haxelib install hxnodejs
```

Currently, this conversion fails (will make another issue), but I don't think it has anything to do with the `@types/...`

**Comment by haxiomic** [comment]
I agree, this is definitely worth documenting – I'll put it in the readme

The general rule is `dts2hx {module-name}` where `module-name` is the same module name you'd use in typescript with the same lookup behavior, so in the case of lowdb, this also works
```
npm install lowdb
npm install @types/lowdb
npx dts2hx lowdb
```

For local typescript files, say 'types.d.ts' you do: `dts2hx ./types`

**Comment by haxiomic** [comment]
Added docs in https://github.com/haxiomic/dts2hx/commit/5707c92cc9723fd70404afe14623c106397ecac9
