### ISSUE TITLE
express generation repeats

### ISSUE THREAD

**Issue by MatthijsKamstra** [haxiomic/dts2hx#68]
I think I found an error in converting ts to hx

But also not 100% sure (could not find the answer in the ts files), so I am trying to treat lightly here...

I am updating the node.js haxe examples I have and indeed the **Express** hello world is working!

If you start adding stuff it seems that the overloads are not complete (have checked against typescript example with express and that confirms my suspicion )

1. this should be possible `app.get('/', (req, res) -> { }`
2. this should work`app.use(Morgan.call('dev'));`
3. this should work `app.use(Express.static_.call('public'));`

## My first clue:

```
@:overload(function(handlers:haxe.extern.Rest<RequestHandlerParams<ParamsDictionary, Dynamic, Dynamic, qs.ParsedQs>>):Express { })
@:overload(function<P, ResBody, ReqBody, ReqQuery>(path:PathParams, handlers:haxe.extern.Rest<RequestHandler<P, ResBody, ReqBody, ReqQuery>>):Express { })
@:overload(function<P, ResBody, ReqBody, ReqQuery>(path:PathParams, handlers:haxe.extern.Rest<RequestHandlerParams<P, ResBody, ReqBody, ReqQuery>>):Express { })
@:overload(function(path:PathParams, subApplication:Application):Express { })
dynamic function use(handlers:haxe.extern.Rest<RequestHandler<ParamsDictionary, Dynamic, Dynamic, qs.ParsedQs>>):Express;
```	

First overload and last function are the same, and I am not able to do `app.get('/', (req, res) -> { }`

## Second clue:

```
@:overload(function(path:String, options:Dynamic, ?fn:express_serve_static_core.Errback):Void { })
function sendFile(path:String, ?fn:express_serve_static_core.Errback):Void;
@:overload(function(path:String, options:Dynamic):Void { })
@:overload(function(path:String, fn:express_serve_static_core.Errback):Void { })
@:overload(function(path:String, options:Dynamic, fn:express_serve_static_core.Errback):Void { })
function sendfile(path:String):Void;
```

two function sendfile, (not sure if that is possible). And two the same overloads..

this should work: `res.sendfile(Node.__dirname + '/public/index_advanced.html');`

- edit: research: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/express/express-tests.ts

**Comment by haxiomic** [comment]
Because haxe has more strict typing rules than typescript you have to be a little careful translating typescript directy

For example, in haxe you need to supply all the arguments to a function, for example:
```typescript
var fn: (str:string,  n:number) => void = (str) => { /* ommited argument for 'n' but typescript doesn't complain */ };
```
```haxe
var fn: (String,  Float) -> Void = (str) -> { /* TYPE ERROR:  missing second argument */ };
```
Here's some notes on this specifically for express 
https://community.haxe.org/t/how-does-one-use-routes-in-express/2701/3?u=haxiomic

Not sure what the return value of `Morgan.call('dev')` is but `Express.static_.call('public')` returns a handler that looks correct – could you copy the error you're getting here?

The two sendfile functions are correct and are in the express type definitions. They have different casing, the 'sendfile' variant is deprecated. It would be nice to automatically add the deprecated meta for this, this is in the roadmap

**Comment by haxiomic** [comment]
I've added a bit more to the express sample code https://github.com/haxiomic/dts2hx/commit/d242e666922d382ae1aea93f870355f1bc26088e

**Comment by MatthijsKamstra** [comment]
I  indeed didn't see the subtle difference between `sendfile` and `sendFile`

**Comment by MatthijsKamstra** [comment]
About express, I am not getting errors anymore.. But it just doesn't work (the server) `http://localhost:3000/test`.

But I was watching tv and programming at the same time, so my attention was split.. will revisit when I can

**Comment by haxiomic** [comment]
Copy over the haxe code you use and I can test here
