### ISSUE TITLE
lowdb conversion has plugins

### ISSUE THREAD

**Issue by MatthijsKamstra** [haxiomic/dts2hx#69]
Hi !

lowdb now converts!! (😱), but it also has plugins that are not converted...

is there a way to force the generation of the plugins as well?

<img width="264" alt="Screenshot 2020-10-22 at 22 55 09" src="https://user-images.githubusercontent.com/907219/96929148-feb96400-14b9-11eb-974f-cd6e7e26e680.png">

something like ?:

`npx dts2hx @types/lowdb/adapters/FileSync.d.ts`

## example code lowdb

js

```js
const adapter = new FileSync('db.json')
const db = low(adapter)

// Set some defaults (required if your JSON file is empty)
db.defaults({ posts: [], user: {}, count: 0 }).write()
```
haxe

```haxe
var adapter = new FileSync('db.json')
var db = Lowdb.call(adapter);

// Set some defaults (required if your JSON file is empty)
db.defaults({ posts: [], user: {}, count: 0 }).write();
```

**Comment by haxiomic** [comment]
That’s the right idea, but try without the .d.ts extension (it uses the same module referencing system as typescript)

**Comment by haxiomic** [comment]
It’s on the roadmap for there to be an option to convert all types found in a module

**Comment by haxiomic** [comment]
I think the .d.ts thing is a common point of confusion so I've just tweaked it so it will work for both b404bf4a452184c86306cb7523a8f74fd7acb504

**Comment by MatthijsKamstra** [comment]
> It’s on the roadmap for there to be an option to convert all types found in a module

Yes I noticed this in the readme... which I didn't read before I dove in ... 
But now I know and will make the adjustments in a different branch

so thx!
