### ISSUE TITLE
npx dts2hx @tensorflow/tfjs got many error?

### ISSUE THREAD

**Issue by sonygod** [haxiomic/dts2hx#71]
npx dts2hx @tensorflow/tfjs got many error?

is tensorflow self error?

**Comment by sonygod** [comment]
TensorLike1D.hx 

should be 

`typedef TensorLike1D = ts.AnyOf8<js.lib.Float32Array, js.lib.Int32Array, js.lib.Uint8Array, Array<Float>,Array<Int>, Array<Bool>, Array<String>, Array<js.lib.Uint8Array>>;`

and default miss `Array<Int>`
  

and the type.ts

```
/** @docalias TypedArray|Array */
export type TensorLike1D = TypedArray|number[]|boolean[]|string[]|Uint8Array[];
```

**Comment by haxiomic** [comment]
number maps to Float in haxe, typescript does not have a concept of Int, so number[] is Array<Float>

Could you copy and paste how it’s currently generated?

**Comment by sonygod** [comment]
```
package tensorflow.tfjs_core.dist.types;

typedef TensorLike1D = ts.AnyOf7<js.lib.Float32Array, js.lib.Int32Array, js.lib.Uint8Array, Array<Float>, Array<Bool>, Array<String>, Array<js.lib.Uint8Array>>;
```

**Comment by haxiomic** [comment]
@sonygod agreed, Array<Int> should unify with number[], so I'll replace instances of `number[]` with `Either<Array<Float>, Array<Int>>`

**Comment by haxiomic** [comment]
I implemented this but wasn't happy with the result, it clutters and makes for confusing code in other places

Say you have a method like `sizes(): number[]`, this now translates to `sizes(): Array<AnyOf2<Float, Int>>` which while technically correct I don't think is clearer than `Array<Float>`. In the future haxe may handle this unification itself anyway. So I'm going to leave this as-is and close the issue

Here's the change I attempted
https://github.com/haxiomic/dts2hx/compare/improve-array-number-71
