### ISSUE TITLE
Interface -> Function types if interface has no fields

### ISSUE THREAD

**Issue by haxiomic** [haxiomic/dts2hx#73]
See https://community.haxe.org/t/js-extern-trouble-how-to-make-a-callback-function-out-of-a-typedef/2769/2?u=haxiomic

```typescript
export interface SimpleGitTaskCallback<T = string> {
    (err: null, data: T): void;
    (err: Error): void;
}
```

To

```haxe
typedef SimpleGitTaskCallback<T> = ts.AnyOf2<(err: js.lib.Err) -> Void, (err: Dynamic, data: T) -> Void>
```

**Comment by haxiomic** [comment]
Need to consider that another class or interface may implement /extend these types and use the 'I' type variant there

**Comment by Kyliathy** [comment]
Yup. Works like a charm! :). Thank you once more!
