### ISSUE TITLE
Cannot redeclare block-scoped variable 'console'

### ISSUE THREAD

**Issue by sonygod** [haxiomic/dts2hx#80]
dts2hx@0.15.3

```
npm install @types/wechat-miniprogram

npx dts2hx wechat-miniprogram
```

**Comment by haxiomic** [comment]
This is an issue in the externs themselves and I get the same error when I use them: if I make a new file named `test.ts` that includes the wechat type definitions:
```typescript
/// <reference types="wechat-miniprogram" />
```

And then do `tsc test.ts`, I get
```
../../.npm-global/lib/node_modules/typescript/lib/lib.dom.d.ts:18958:13 - error TS2451: Cannot redeclare block-scoped variable 'console'.

18958 declare var console: Console;
                  ~~~~~~~

  node_modules/@types/wechat-miniprogram/lib.wx.api.d.ts:18650:15
    18650 declare const console: WechatMiniprogram.Console
                        ~~~~~~~
    'console' was also declared here.

node_modules/@types/wechat-miniprogram/lib.wx.api.d.ts:18650:15 - error TS2451: Cannot redeclare block-scoped variable 'console'.

18650 declare const console: WechatMiniprogram.Console
                    ~~~~~~~

  ../../.npm-global/lib/node_modules/typescript/lib/lib.dom.d.ts:18958:13
    18958 declare var console: Console;
                      ~~~~~~~
    'console' was also declared here.
```

The good news is the conversion still works just fine and this is more of a warning from the typescript compiler. Nevertheless, if there are special ts config options that will resolve these error messages you can pass them in using `--tsconfig`

**Comment by sonygod** [comment]
hi,@haxiomic ,this is only for auto-complete only, you can't run without a Wechat app environment.:)

**Comment by haxiomic** [comment]
The error I posted is a ts compiler-time/autocomplete error (haven’t tested runtime)

**Comment by sonygod** [comment]
My screenshot show ide auto complete everything is OK use that file
