### ISSUE TITLE
extends tyep error.

### ISSUE THREAD

**Issue by sonygod** [haxiomic/dts2hx#85]
cocoscreator.d.ts

`static loadRes(url: string, type: typeof cc.Asset): void;
`
to haxe
```haxe
static function loadRes(url:String, type:{ var prototype : Asset;});

```

and 

```haxe
@:native("sp.SkeletonData") extern class SkeletonData extends global.cc.Asset 
```

when type

```haxe
Loader.loadRes('loadSpine/alien-ess',SkeletonData);
```

will throw this compile error

```
for argument type:{prototype:Asset}

error: global.sp.SkeletonData should be global.cc.Asset
have: { prototype: global.sp.SkeletonData }
want: { prototype: global.cc.Asset }
For function argument 'type'diagnostics(2)
```

**Comment by haxiomic** [comment]
hmm, the type looks as correct as we can make it but the error seems to be more about haxe's more restrictive type system. I don't think there's much we can do here. Bet solution is to use cast here: `Loader.loadRes('loadSpine/alien-ess', cast SkeletonData);`
