### ISSUE TITLE
Field of type Void with monaco-editor

### ISSUE THREAD

**Issue by Gama11** [haxiomic/dts2hx#96]
With

- monaco-editor 0.26.1
- dts2hx 0.15.3

The generated `monaco_editor.Token` looks like this:

```haxe
package monaco_editor;

@:jsRequire("monaco-editor", "Token") extern class Token {
	function new(offset:Float, type:String, language:String);
	var _tokenBrand : Void;
	final offset : Float;
	final type : String;
	final language : String;
	function toString():String;
	static var prototype : Token;
}
```

Which fails to compile because of `var _tokenBrand : Void;`.

**Comment by haxiomic** [comment]
Thanks for the report :), I've added a new support type `ts.Undefined` which aliases to `Any`, to serve as documentation that this type is `void` in ts

Try again dts2hx 0.16.0
