### ISSUE TITLE
Error: Internal error: Reached type-depth limit, stopping further type conversions. This indicates unbound recursive type conversion

### ISSUE THREAD

**Issue by Jarrio** [haxiomic/dts2hx#99]
Trying to convert discord.js externs is leading to the above error message.

Repro:
```
npm install discord.js@13.2.0
npx dts2hx discord.js
```

**Comment by haxiomic** [comment]
#91

**Comment by haxiomic** [comment]
closing as dupe (but recognize it's an issue to be solved, should be fixed when upgrading to TS4!)
